config/routes.rb
DeviseExample::Application.routes.draw do
  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout' } do
    get "/register" => "devise/registrations#new"
    get "/forgot" => "devise/passwords#new"
    get "/login" => "devise/sessions#new"
    delete "/logout" => "devise/sessions#destroy"
  end
  devise_scope :user do 
    get '/users/current' => "users#current", :as => :current_user
    resources :users, :only => [:index, :show]
    root :to => "users#current"
  end
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Others available are:
  # :token_authenticatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, # :validatable,
         :confirmable, :lockable, :timeoutable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  # validates_uniqueness_of :email, :scope => authentication_keys[1..-1], :case_sensitive => false, :allow_blank => true
  validates :email,
    :presence => true, 
    :uniqueness => { :case_sensitive => false, :allow_blank => true },
    :format => { :with  => /^([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})$/i, :allow_blank => true }

  validates :password, 
    :presence => true, 
    :confirmation => true, 
    :length => { :within => 6..40 }, 
    :format => { :with => /^(?=.*\d)(?=.*[A-Z])(?=.*[a-z])(?=.*(\W|_))([\x20-\x7E])*$/, :message => 'must contain at least one upper-case, lower-case, digit and special character' },
    :if => :password_required?

    def password_required?
      !persisted? || !password.nil? || !password_confirmation.nil?
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController
  before_filter :authenticate_user!

  def index
    @users = User.all
    render_with_scope :index
  end

  def show
    @user = User.find(params[:id])
    render_with_scope :show
  end

  def current
    @user = current_user
    render_with_scope :show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def password_meter()
    html = render :partial => 'devise/shared/password_meter'
  end

  def display(user, text)
    user == current_user ? text : truncate(text, :length => 7)
  end
end

app/views/layouts/application.html.haml
!!!
%html{:xmlns => "http://www.w3.org/1999/xhtml", "xml:lang" => "en", :lang => "en"}
  %head
    %title DeviseExample
    = stylesheet_link_tag :all, :cache => false
    = javascript_include_tag :defaults
    = csrf_meta_tag
  %body
    - if current_user
      = link_to "Account", user_path(current_user)
      = link_to "Logout", logout_path, :method => :delete, :confirm => "Are you sure you want to logout?"
    - else
      = link_to "Register", register_path
      = link_to "Forgot Password", forgot_path
      = link_to "Login", login_path

    %p{ :class => 'notice' }= notice
    %p{ :class => 'alert' }= alert
    = yield

app/views/users/index.html.haml
%h1 Users

%table
  %tr
    %th
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= display(user, user.email)
      %td= link_to 'Show', user_path(user)
      // TBD - users should only have access to their own account at the controller level
      - if user == current_user
        %td= link_to 'Edit', edit_user_registration_path
        %td= link_to 'Destroy', user_registration_path, :confirm => 'Are you sure?', :method => :delete

app/views/users/show.html.haml
%p
  %b Email:
  = display(@user, @user.email)

%p
  %b Login count:
  = @user.sign_in_count

%p
  %b Last request at:
  = "Not yet supported" # = @user.last_request_at

%p
  %b Current login at:
  = @user.current_sign_in_at

%p
  %b Current login ip:
  = display(@user, @user.current_sign_in_ip)

%p
  %b Failed login count:
  = @user.failed_attempts

%p
  %b Last login at:
  = @user.last_sign_in_at

%p
  %b Last login ip:
  = display(@user, @user.last_sign_in_ip)

- if @user == current_user
  = link_to 'Edit', edit_user_registration_path
  \|
  = link_to 'Destroy', user_registration_path, :confirm => 'Are you sure?', :method => :delete
  \|
= link_to 'Users', users_path